package com.example.nameandnumber;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {

    EditText editText;
    Button button;
    TextView numTextView, aboutTextView;
    String mName;
    int mTotal, nameLength;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        editText = (EditText) findViewById(R.id.input_field);
        button = (Button) findViewById(R.id.calcButton);
        numTextView = (TextView) findViewById(R.id.finalAns);
        aboutTextView = (TextView) findViewById(R.id.aboutNum);

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mTotal = 0;
                mName = editText.getText().toString();
                nameLength = mName.length();
                getTotal();
                calculate();
                numTextView.setText("" + mTotal);
                aboutNum();
            }
        });
    }

    private void getTotal() {
        for (int i = 0; i < nameLength; i++) {
            if (mName.charAt(i) == ' ' || mName.charAt(i) == '.' || mName.charAt(i) == '0') {
                mTotal = mTotal + 0;
            } else if (mName.charAt(i) == 'a' || mName.charAt(i) == 'A' || mName.charAt(i) == 'i' || mName.charAt(i) == 'I' || mName.charAt(i) == 'j' || mName.charAt(i) == 'J' || mName.charAt(i) == 'q' || mName.charAt(i) == 'Q' || mName.charAt(i) == 'y' || mName.charAt(i) == 'Y') {
                mTotal = mTotal + 1;
            } else if (mName.charAt(i) == 'b' || mName.charAt(i) == 'B' || mName.charAt(i) == 'k' || mName.charAt(i) == 'K' || mName.charAt(i) == 'r' || mName.charAt(i) == 'R') {
                mTotal = mTotal + 2;
            } else if (mName.charAt(i) == 'c' || mName.charAt(i) == 'C' || mName.charAt(i) == 'g' || mName.charAt(i) == 'G' || mName.charAt(i) == 'l' || mName.charAt(i) == 'L' || mName.charAt(i) == 's' || mName.charAt(i) == 'S') {
                mTotal = mTotal + 3;
            } else if (mName.charAt(i) == 'd' || mName.charAt(i) == 'D' || mName.charAt(i) == 'm' || mName.charAt(i) == 'M' || mName.charAt(i) == 't' || mName.charAt(i) == 'T') {
                mTotal = mTotal + 4;
            } else if (mName.charAt(i) == 'e' || mName.charAt(i) == 'E' || mName.charAt(i) == 'h' || mName.charAt(i) == 'H' || mName.charAt(i) == 'n' || mName.charAt(i) == 'N' || mName.charAt(i) == 'x' || mName.charAt(i) == 'X') {
                mTotal = mTotal + 5;
            } else if (mName.charAt(i) == 'u' || mName.charAt(i) == 'U' || mName.charAt(i) == 'v' || mName.charAt(i) == 'V' || mName.charAt(i) == 'w' || mName.charAt(i) == 'W') {
                mTotal = mTotal + 6;
            } else if (mName.charAt(i) == 'o' || mName.charAt(i) == 'O' || mName.charAt(i) == 'z' || mName.charAt(i) == 'Z') {
                mTotal = mTotal + 7;
            } else if (mName.charAt(i) == 'f' || mName.charAt(i) == 'F' || mName.charAt(i) == 'p' || mName.charAt(i) == 'P') {
                mTotal = mTotal + 8;
            } else {
                Toast.makeText(MainActivity.this, "There is an unrecognised character in the name. Please check and try again!", Toast.LENGTH_SHORT).show();
            }
        }
    }

    private void calculate() {
        int sum = 0;
        while (mTotal > 9) {
            sum = 0;
            while (mTotal > 0) {
                int rem;
                rem = mTotal % 10;
                sum = sum + rem;
                mTotal = mTotal / 10;
            }
            mTotal = sum;
        }
    }

    private void aboutNum() {
        if (mTotal == 1) {
            aboutTextView.setText("In Numerology, each of the nine single-digit numbers has a personality -- a limited range of qualities and traits that makes it unique and recognizable. To me each number is a character, like any human being. In order to understand how numbers affect us based on their location in the chart, it helps to get to know each single digit number as if it were a person.\n" +
                    "\n" +
                    "The goal is to get beyond each number being just a list of positive and negative qualities and to, instead, make each number come alive -- to sense how the numbers play off of each other. If you sense some exaggeration in my descriptions, remember that these nine \"individuals\" are extremes by their very nature (while we, as human beings, are made up of a mixture of all the numbers' traits).\n" +
                    "\n" +
                    "Among the nine single-digit numbers, the 1 takes a special place. From a spiritual perspective, it is the number of creation, the primal force from which all other numbers spring forth (as opposed to the often quoted zero from which, by definition, nothing could possibly come into being). It is said that when you truly understand the place and function of this most primal of all numbers, you will know all there is to know and enlightenment is yours. This statement, of course, does not apply to an understanding of the number 1 from a Numerologist's perspective alone, but perhaps that is a good place to start, as the personality of the number 1 aligns nicely with its more elevated spiritual symbolism.\n" +
                    "\n" +
                    "The 1 is a doer, a powerful force that produces results and does not allow anything or anyone to limit its potential. The 1 is aggressive, a necessary energy for creating and producing. The 1 is always in the forefront: a spearpoint directing and leading others. The shape of the number 1, just like the shape of all other symbols, reflects its meaning; it walks upright with pride and purpose. Strong, determined, unwavering and with specific goals in mind, the 1 can turn dreams and ideas into reality. It pushes obstacles aside or simply drills right through them.\n" +
                    "\n" +
                    "The 1 grows, transforms and improves in perpetuity, precisely the way Mother Nature does. After all, nature's primal force and most basic building block is the number 1. Nature knows no mercy and its cruelty can be heartbreaking. However, it knows balance and gives life indiscriminately and without judgment. Scientists sometimes compete with nature, genetically altering fruits or breeding bugs for specific purposes. An understanding of nature teaches us that this is never a good idea and almost always produces unexpected backlashes. The number 1 has a similar built-in perfection and balance; you can force a change here or there, but negative repercussions are likely.\n" +
                    "\n" +
                    "The 1 tends to have a simple, straightforward view of life and its many complexities. It trusts its own ability to separate right from wrong. It doesn't waste time on abstract ideas or anything else that isn't in line with its pursuit of results. The 1 is no preacher, no philosopher, no spiritual explorer, no dreamer and certainly not an idealist. It is a pragmatist, a ruthless conqueror and a warrior extraordinaire. It is individualistic and independent to a fault. It will attempt to force its values and opinions on you but it won't accept, or even listen to, yours.\n" +
                    "\n" +
                    "The 1 does not hesitate when it senses a need for confrontation. It is jealous and extremely stubborn, but also courageous and willing to try anything new if it sees promise, even at great danger. It is, if you haven't guessed, the most masculine of all numbers. There is a certain quality, a sense of honor and responsibility that demands our respect, and it has a sense of justice that cannot be denied. The number 1 cannot witness injustice without jumping in and setting things straight.\n" +
                    "\n" +
                    "Its purity of purpose is an admirable quality of the number 1. It sees things for what they are and hypocrisy doesn't stand a chance. Befriend a 1 and you have a friend for life. You can poke fun at a 1 and not have to worry about hurt feelings. A 1 has a great capacity for humor, including the self-deprecating kind. If, however, you try to cater to a 1 to win its love or friendship, you'll lose its respect instead. Stand up to a 1 and you may lose the fight, but you'll gain its admiration. If you are in trouble and need help, the number 1 is who you want on your side -- there is no more dedicated protector or braver partner. If you are in love, the number 1 is the most difficult of all lovers: demanding, jealous, confrontational and impatient. If you find yourself in the service of a 1, you will be pushed to the limit, abused at all hours, and incapable of living up to its expectations. But you will also, without a doubt, become the best you could ever be. If the 1 is your enemy, you will be crushed without mercy.\n" +
                    "\n" +
                    "If you yourself are a 1, your happiness and satisfaction will come from your work more than from any other source. And if it was possible for a person to be fully and truly a 1 and only a 1, that individual would be successful and intimidating, as well as extremely unpleasant and dangerous.");
        } else if (mTotal == 2) {
            aboutTextView.setText("As the most feminine among all numbers, the 2 is also the most underestimated -- at least, when it comes to power and strength. After all, she is almost always gentle, tactful, diplomatic, forgiving and understanding. Certainly, she likes to keep the peace and will avoid confrontations as much as possible.\n" +
                    "\n" +
                    "If you look at the shape of the 2, however, you will recognize a symbolic representation of the ultimate survivor and an extremely resilient force. Her shape, as if bent on a knee with her head and back bowed in humility and servitude, makes it easy to dismiss her as weak and powerless. This is in stark contrast to the power and pride of the mighty and masculine 1, who will not bow for anyone at any price. However, when enough pressure is applied to the powerful warrior we see in the number 1, he will break and shatter and be done with.\n" +
                    "\n" +
                    "On the other hand, when the humble and feminine 2 finds herself under attack and burdened with a crushing weight, she will bend, she will bend as much as needed. And when the weight is removed, her elastic, flexible nature allows her to come right back up, seemingly with little harm done, and she will continue to play her role.\n" +
                    "\n" +
                    "Her strength and power is resilient and lasting, just as the shape of the number 2 reflects that so beautifully. There is much more to her than meets the eye; she is often the true power behind the throne. As we stand in awe to the leadership and decisive actions of the 1, his strength and cunning relies on the clever and insightful advice of his greatest ally, the number 2.\n" +
                    "\n" +
                    "Unnoticed and operating from the shadows, she is the Mata Hari who outwits other spies and diplomats with her grace, her sensuality, her flattering attention and her gentle force of persuasion. She is smart and understands the underlying qualities that make people do this or do that. A born psychologist, there is not much about human nature that escapes her. She often controls the outcome of certain events without anyone else noticing or acknowledging. In fact, the credit quite often goes to some other entity when it should be hers. This does not bother her, because among her best qualities is patience. She knows her time will come. But even if she does not always get the recognition she deserves, she tends to take a special place in the hearts and minds of others due to her sophistication, her grace, her style and her excellent taste in art and music.\n" +
                    "\n" +
                    "The 2 has an in-born sense of music and rhythm that makes her popular among any social crowd, and it is in the lighthearted arena of play and art that she shines as a dancer and a conversationalist. Within a social environment, perhaps her most important asset is a sense of humor that is witty and self-depreciating, but never slapstick or juvenile, as she is far too sophisticated for that.\n" +
                    "\n" +
                    "If the Greek god Zeus could be compared to the number 1, then his wife and sister Hera would represent the number 2. And like Hera, the number 2 is jealous and mean-spirited when other forces reach for her man. Because as gentle and loving as she is most of the time, her anger is formidable and another side of her comes out when she feels crossed or mistreated -- a side that can be mean and vengeful, cruel and unrelenting. She will claw her adversary to pieces and never look back in regret or remorse. What is hers is hers, and you are well-advised to remember that, as many Greek gods and half-gods found out the hard way.\n" +
                    "\n" +
                    "As a partner, the number 2 is an invaluable asset. She will defend you at any cost and her loyalty is unshakeable. However, she is emotional and demanding, and expects to be treated like a princess. She is devoted to you, but she also expects you to be devoted to her. At times, she is a true drama queen, and when that happens you may know for sure that you have not paid enough attention lately. She is not particularly materialistic, but if you don't show up with gifts or flowers every once in a while, she will let you know in no uncertain terms that you are not measuring up. She will throw the occasional tantrum, but if you respond with love and attention she will make it up to you in proper fashion.\n" +
                    "\n" +
                    "In short, the number 2 is a sensual, graceful, loyal partner who can be a bit demanding, but is worth the trouble. And there is another important aspect to the number 2. As the most intuitive of all single-digit numbers, she is drawn to the occult (only the double-digit 11 surpasses her in that department). However, the real value of her intuitive prowess is in the way she interacts with others; it is the true basis of her tact and understanding. Like a good politician, which she can certainly be if needed, she often understands the true motivations of others better than they do, and her clarity and her powers of observation often help others to understand themselves better.\n" +
                    "\n" +
                    "On top of her jealousy, her vengeful nature when she feels mistreated and her cruelty when punishing adversaries, the 2 can also be critical and verbally abusive. Her ability to pout and sulk, her bouts of bad temper for trivial reasons and her extended periods of indifference can drive any sane person crazy. On top of that, she is capable of displaying the most illogical reasoning, and a verbal argument can feel like trying to slice water with a knife; nothing you say seems to have any effect. Generally, the best thing to do when a 2 behaves like that is to get out of her way for a while -- and then reappear with a big bouquet of flowers, and smile like nothing ever happened.");
        } else if (mTotal == 3) {
            aboutTextView.setText("The number 3 is like a gifted teenager who is still under the protection of its parents: a bit spoiled, certainly scattered and perpetually in need of guidance. However, the most obvious traits of the 3 are in the creative field. A powerful need to express feelings, ideas and visions of the imagination, coupled with an extroverted personality, makes it likely that a person with 3s in key points of their Numerology chart will seek a career in art, especially the verbal arts. His or her social skills are also excellent. Charm, wit and a sense of humor help a 3 individual along his or her path, and if that weren't enough, good looks and compelling charisma make this \"kid\" particularly attractive.\n" +
                    "\n" +
                    "No wonder so many are drawn to those with 3s in their charts. Followers are even willing to forgive less favorable traits exhibited by 3s, like a lack of focus and direction, a tendency to procrastinate, an inability to finish projects and an unwillingness to take responsibility. On the other hand, there is a superficial side to the 3 that can be harder to look past: a narcissistic streak, a vanity, a need to be the center of attention. It is easy for the optimistic 3 to enjoy day-to-day life as long as all is well, but when challenging issues arise, it can become quickly apparent that most of the 3's focus has been on that sunny exterior, leaving its internal fortitude lacking. Without much moral strength or spiritual depth, a 3 can easily succumb to difficulties unless friends and family move in to support it.\n" +
                    "\n" +
                    "For the 3 to become a well-rounded, balanced and happy person, it must learn discipline. Some lucky 3s who exhibit talent early in life (such as gifted dancers or musical prodigies) are placed in an environment with just the sort of discipline that a 3 needs to protect these talents. Another unique quality of the 3 is its tendency to be \"lucky,\" or rather, to be in the right place at the right time. This may be connected to its innate sense of rhythm; timing can be measured in seconds or in years, by the beating of a heart or by the movement of the stars. It is all only a matter of scale, either way, the 3 seems to be in tune with the cyclical nature of our surroundings. Relationships are a bit of a challenge for the 3 -- at least those that include long-term commitment and loyalty. With plenty of acquaintances (probably more than is healthy), when true depth and intimacy enters the picture, this \"kid\" turns tail and runs. The 3 has a nasty jealous streak, too, causing conflicts when those it has rejected move on in search of more meaningful bonds. This jealousy stems from the fact that the 3 knows, deep down inside, that it has only been skimming the surface of life since birth. As a result, the 3 feels a deeply hidden sense of insecurity, a sense that others know things that have thus far escaped the 3. This is not entirely incorrect and, when confronted with this reality, it leaves the 3 devastated and helpless.\n" +
                    "\n" +
                    "There is perhaps nothing more painful than to watch the sunny, buoyant 3 crash into a vulnerable heap of self-pity. And yet, this can be the best thing ever to happen to this shallow creature, as this sometimes represents a turn-around. Once a 3 finds the motivation and enthusiasm to dig deeper into the realities of life (something that will only happen when it has had to confront itself), its happy surface has the potential to be replaced by the quiet serenity that only true wisdom brings. Such a \"transformed\" 3, rare as it is, is truly a thing to behold.\n" +
                    "\n" +
                    "No human being is ever represented by just one number, but rather is a mixture of several, if not all, of the numbers. Those who have been blessed with a heavy dose of 3s in their charts tend to have an easier time being happy, optimistic and playful creatures. However, this kind of \"joie de vivre\" can leave those same people unprepared for the more demanding experiences that life inevitably brings. And while the western mindset focuses on happy moments as the ideal, the unhappy experiences can be the ones that bring a much greater depth and quality to our lives.\n" +
                    "\n" +
                    "For the number 3, happiness may be easy to achieve, but is almost always a consequence of something materialistic or fleeting (a new car, a new relationship, a sunny day, etc.). A higher happiness, one that is not a consequence of any particular event but is truly the result of a deep appreciation towards life itself, is worth a million times more than the aforementioned shallow kind. The biggest challenge for the number 3 is to recognize this, to learn that the real beauty of life is found not in our possessions or illusions, but rather is hidden inside our fellow human beings. After all, it is being human that allows us the potential to experience what has been called the impossible achievement: to enter the realm where the mortal and the immortal meet.\n" +
                    "\n" +
                    "If the 3 can ever defy the odds to achieve this rare and amazing state of being, the fact that it has had to travel so far to reach such a height makes this number uniquely qualified to guide and help others reach the same goal.");
        }
        else if (mTotal == 4) {
            aboutTextView.setText("The 4 is without a doubt masculine, reflecting strength and stability. His chief characteristics are dependability, productivity, punctuality and obedience. He is trustworthy, patient, conventional and a traditionalist. He is a bit boring and not much of a social person, preferring to toil in quiet obscurity. He works steadily and can be very persistent. He finds great satisfaction in his accomplishments and favors results over financial reward or public recognition. He is humble, dresses conservatively and blends in with his surroundings.\n" +
                    "\n" +
                    "He is average in looks, physically healthy and strong, neat and clean ... but unremarkable. He does not like to draw attention to himself, but will fight you tooth and nail if you try to muscle in on his territory. He believes in effort and control, and is certainly goal-oriented, but his goals are simple and down to earth. He is not a visionary, but notices every detail. He is capable, has an excellent memory and doesn't cut corners. He is the perfect employee, but doesn't tend to do well in social environments.\n" +
                    "\n" +
                    "If you look at the shape of the number 4, you will see that the hard angles are a proper symbolic representation of this rather straight-edged workaholic, who is neither creative nor artistic, but is good at working with his hands. Many craftsmen and skilled laborers have the 4 prominently in their charts. He is a good provider, but demands discipline and loyalty, and in some cases takes discipline too far. He can't handle chaos and is prone to panic attacks if it appears he might not have things fully under control. The 4's imagination is not well developed, and his views are usually narrow-minded and conventional. The 4 tends to be religious without questioning established doctrine, preferring to parrot the beliefs of his peers, feeling safe and secure in the predictable, unchanging nature of a tight discipline. More than any other number except perhaps the 7, 4s are found in the charts of monks, priests and other religious leaders. Many also become excellent managers and organizers, and it is not at all uncommon to find a 4 in the upper echelons of business and government. The 4 will work hard and can be driven to reach the top of his profession, but in striving to reach the top he usually finds that his greatest obstacle is himself: his lack of social skills, his inability to relate to the mundane issues of his co-workers and his lack of intuition.\n" +
                    "\n" +
                    "The 4 doesn't like to make waves, but values his moral convictions and will not back down when convinced that he is doing \"the right thing.\" However, he can also be intolerant and, when faced with people from other cultures, countries or races, his insecurity can turn him into a cruel bigot. Many 4s choose a career in the military, where their obedient, disciplined nature is right at home. They especially thrive when they are assigned duties that include administrative and organizational work.\n" +
                    "\n" +
                    "As with any number, there are some contradicting traits within the 4. For instance, while he is not particularly social or fun-loving, the 4 sometimes reveals an entertainingly dry sense of humor. Further, although he is a strict and disciplined parent, the 4 is also extremely devoted and will walk through fire to get his kids what they need.\n" +
                    "\n" +
                    "My description of the 4 is, not surprisingly, almost the exact opposite of my description of the 3. This is to be expected, as every number is, in important ways, a counterpoint to the one that directly precedes it. The 2 is the polar opposite of the 1, the 3 displays traits that are directly opposed to those of the 2, and so forth. And of course the differences between the 5 and the 4 are like night and day!");
        }
        else if(mTotal == 5) {
            aboutTextView.setText("The number 5 is the most dynamic and energetic of all the single-digit numbers. It is unpredictable, always in motion and constantly in need of change. Although it is molded from an almost equal mix of masculine and feminine qualities, in general the 5 is slightly more feminine -- albeit a daring, tomboyish kind of feminine, with nothing demure or submissive about her.\n" +
                    "\n" +
                    "The 5 is extremely independent in mind and soul. She is an adventurer and a risk-taker who has a hard time staying in one place, in one job, in one house or in one relationship. Change is an absolute necessity, and yet the 5 is surprisingly loyal. The 2 and 6 are the most harmonious relationship numbers but either one will, when temptation is strong enough, cheat on his or her partner. The 5 will not. The 5 may break off a relationship due to her restless nature, but while in a relationship she will not deceive her partner. However, when she is not in a relationship she considers herself free to date anyone she chooses and has no problem going out with a different person every day of the week (and you better not try to tell her she should limit herself in any way, at least not if you want to stay on her good side).\n" +
                    "\n" +
                    "The 5 generally does not find a suitable career until she has tried a number of different jobs, many of them lasting barely long enough to warrant a full paycheck, especially if there is any kind of routine involved; boredom sets in almost immediately and the 5 simply cannot put up with anything predictable or repetitive. But again, the 5 will surprise her friends and family once she does find her niche, usually after age 30, as her focus, energy and quick mind help her scramble up the ladder faster and with less apparent effort than anyone else. Many 5s take up careers that require travel or otherwise offer a change of environment regularly, becoming tour guides, salespeople, small business owners, independent consultants, lawyers and so forth.\n" +
                    "\n" +
                    "The 5 can adjust quickly to pretty much anything coming her way, and that includes the work environment. On top of that, the 5 is usually tall and good-looking, charming, and charismatic -- all qualities that support her in her career once she sets her mind to it. In addition, the 5 is versatile, adaptable, smart, progressive and tolerant. Anything conventional bores her, while she is drawn to the eccentrics and misfits of society. She is a social creature, funny and uplifting, and very good at making others feel comfortable around her. She is generally well-liked and is often surrounded with friends and acquaintances. However, she also tends to polarize people and those that don't like her tend to be the uptight, self-righteous and judgmental kind.\n" +
                    "\n" +
                    "But perhaps the most dominating trait in the 5 is her uncompromising demand for freedom in thought and action. She makes up her own mind, rebels against any and all dogmas and ideologies, and does not allow herself to be absorbed into clubs, cults, religious sects or ideologies of any kind. Her adventurous, daredevil nature may get her to ride motorcycles but she will not ride with a large group. Chances are she will be rather opinionated and passionate about political issues, but she will not be a member of any party or be nailed down in any way. She changes her mind regularly, but never without good reason. She cannot be controlled but she is flexible and can be converted if the argument is solid and makes sense. She has a healthy sense of humor and doesn't sweat the little things, but she carries her heart on her sleeve and it is not at all uncommon for her to give her heart to the wrong person, as she is not the greatest judge of character.\n" +
                    "\n" +
                    "On the negative side, she can be selfish, thoughtless and irresponsible. She rarely considers the future beyond tomorrow or next week, and worrying is not in her nature. She tends to procrastinate and can be unreliable. However, the most common downfall for the 5 is a tendency to experiment with sex, drugs, alcohol and other weaknesses of the flesh. A desire for instant gratification can be her downfall; add to that a sense of invulnerability, lack of discipline and restraint, and you have a recipe for disaster.\n" +
                    "\n" +
                    "The shape of numbers reflect their nature, and just as the 4 is square and grounded, the 5 is a symbol of dynamic motion. The 4 is controlled, measured, synchronized, and static. The 5 is random energy, elastic and constantly in motion.");
        }
        else if (mTotal == 6) {
            aboutTextView.setText("While the 6 is considered the most harmonious of all single-digit numbers, it is not without its flaws and upsets. The most important influence of the 6 is its loving and caring nature. Properly nicknamed the motherhood number, it is all about sacrificing, caring, healing, protecting and teaching others. No family or community can function without the power of the 6 to keep them together and safe. She is the glue that keeps a family or community together.\n" +
                    "\n" +
                    "There are, however, times when the 6 becomes too involved in the lives of those dear to her, to the point that she becomes intrusive and meddling. Other times, she takes her sacrificing nature too far and becomes a doormat to be abused and trampled on. Nonetheless, she is genuinely appreciated and adored in return. For this reason, the 6 is considered the only number harmonious with all other numbers. Creating an environment of peace and harmony is always her strongest impulse. In addition, she loves to teach and guide others, especially the young, old and less fortunate.\n" +
                    "\n" +
                    "The 6 is full of sympathy, and her sense of justice is well developed -- when she perceives injustice, she will sacrifice all her time and effort to set things straight. She almost always favors the underdog, and would never purposely hurt anyone, especially those she considers less fortunate. She has a strong sense of responsibility and can be counted on to do her fair share of the work. She can be demanding, but she is also able and willing to stay in the background when needed, working and caring without any expectation of reward.\n" +
                    "\n" +
                    "The 6 is idealistic, trusting and easy to take advantage of ... which can produce devastating results. She carries her heart on her sleeve and expects the same from others. The role of counselor and advisor comes naturally to her, and many will come to her to cry on her shoulder or to seek her down-to-earth wisdom.\n" +
                    "\n" +
                    "The 6 carries herself well and moves gracefully, yet is warm, funny and jovial. When the 6 is on a career path, she generally goes a long way due, in part, to her sense of duty and responsibility -- but also because she is genuinely respected and well-liked. You will find many 6s in careers such as teaching, healing, counseling, construction, the legal field and law enforcement, especially prison guards.\n" +
                    "\n" +
                    "On the negative side, the 6 can be jealous and small-minded, tending to be more focused on the little details while ignoring the bigger pictures ... usually to her own detriment. She can be a bad judge of character, and has been known to sacrifice herself to a cause or a person even while everyone around her tries to convince her that this cause or person is not worth it.\n" +
                    "\n" +
                    "The 6 is usually rather conventional and must learn to use her own mind instead of simply leaning on the opinions of those close to her. The 6 can also be smug and arrogant, especially toward authority figures or institutions. She can be annoyingly self-righteous and an intolerant religious zealot. The 6 sometimes suffers from anxiety and insecurity, even phobias. A disproportional number of people with OCD have the 6 prominent in their charts.\n" +
                    "\n" +
                    "The 6, while loving, caring and full of sympathy for others, is self-centered and egotistical at heart. If those at the receiving end of her care do not show the attention she craves, she can turn on them, even hurt them. The Munchhausen syndrome is a disorder typical to the negative 6.\n" +
                    "\n" +
                    "No number is without weaknesses and faults, but the 6 is actually the most harmonious and stable among the nine single digits. Yet, perhaps for that same reason, when the unusual happens and the 6 falls into discord and disharmony, it becomes possibly the most destructive and dangerous of all numbers. Beware of a cynical or angry 6 -- she is a merciless wolf in sheep's clothing.");
        }
        else if (mTotal == 7) {
            aboutTextView.setText("The number 7 is the seeker, the thinker, the searcher of Truth (notice the capital \"T\"). The 7 doesn't take anything at face value -- it is always trying to understand the underlying, hidden truths. The 7 knows that nothing is exactly as it seems and that reality is often hidden behind illusions.\n" +
                    "\n" +
                    "A person who has a chart dominated by the 7 is usually easily picked out of a group. He will be somewhat introverted, perhaps shy (not to be confused with low self-esteem), never truly comfortable in social settings. The 7 is the intellectual, but his intellect is not always obvious, especially at an early age (as a child, Einstein was dyslexic and not particularly bright or a good student). His intelligence is that of a dreamer, an intellectual explorer of the obscure, the person who tends to have a somewhat off-beat perspective on the world around him. Many are interested in the metaphysical, not because they are believers, but because it allows access to the ambiguous, abstract world of questions for which there are no clear answers.\n" +
                    "\n" +
                    "The 7 is spiritual, but not religious. In fact, the age-old questions of what life is all about, why am we here, who am we, and so forth, never reach the status of clichés, but are essential to the 7's life-experience, and unless he finds the answers he will not stop looking for them until he dies.\n" +
                    "\n" +
                    "The 7 can be aloof, hates gossip and is immune to small-minded backstabbing. Money means nothing to him and he will never make a choice or a decision based on an expected financial outcome.\n" +
                    "\n" +
                    "There is a dry, usually misunderstood sense of humor to the 7, yet he is unable to remember a single joke. He is not jovial and never superficial. He has excellent taste and a natural love and understanding of art. He dislikes and completely ignores fashion, and is attracted to eccentric, unpopular people. The popular \"beautiful\" but shallow people bore him to no end. He is not usually interested in politics but has a strong sense of justice.\n" +
                    "\n" +
                    "The 7 is physically lanky and tall, but not athletic and doesn't care about sports. 7s are not warriors, but you may find some people with the 7 dominating their charts in the military, most likely as analysts or strategic planners. More often, however, you will find them in the world of academics and science. Police detectives, laboratory researchers and other careers where logical, methodical analysis of facts are the main requirements of the job. 7s are opinionated and tend to know something about everything, which can be annoying. They are not always honest, often choosing a more \"interesting\" truth than the actual truth. Many people are uncomfortable around a 7 due to penetrating eyes and the sense that even when he seems to be listening, he is actually analyzing the shape of your eyes and the crevices of your earlobes.\n" +
                    "\n" +
                    "The 7 tends to be a loner. Women with dominant sevens are often beautiful, if you can get past the granny glasses and the carelessly chosen clothes. They don't like to fuss in front of the mirror, but can be very charming and will take on a room full of men in any discussion, completely unconscious of the fact that many of them have something completely different in mind.\n" +
                    "\n" +
                    "On the negative side, the 7 can be cynical, verbally abusive, arrogant and oblivious of the pain and suffering of others. They can be cold-hearted and cruel showing a lack of empathy. Other people's problems simply don't interest them, yet when it comes to their own troubles, they expect everyone to feel for them. They are terrible and demanding patients, exasperating know-it-alls and just plain inconsiderate and boorish. They can be selfish and anti-social.\n" +
                    "\n" +
                    "What is unique about the 7 is that his (or her) mind is his greatest tool and, at the same time, his greatest limitation. Rational, flexible and hungry for knowledge, the mind of the 7 goes places other numbers rarely attain. His imagination is vast and powerful, which helps to guide him into the spiritual stratosphere few people ever reach -- but it is always mental and rational, never divine. The satisfaction and happiness he finds from mental explorations allows him to spend long hours in solitude and enjoy it. Yet, at the same time, he puts too much faith in the power of the mind, thereby limiting the potential humans have in experiencing the essence of life, as it can be experienced only in feeling and not in words. It is said that if you can speak the Tao, you do not know the Tao; if you can speak the Word, you do not know the Word -- life in its purest form can only be felt and experienced, never rationalized. For the 7 to reach a height of spiritual wisdom, it must, as all others, travel beyond the limitations of the mind and allow divine silence to spill its secrets. It is the essence of the 7 that most symbolizes our struggle to know and understand.\n" +
                    "\n" +
                    "As I've previously mentioned, my descriptions of the single digit numbers are extreme and no human being exists who reflects only one number. I am trying to convey an intuitive and mental connection with the personalities of the single digit numbers; an understanding that eventually brings you to know numbers not because you have memorized a string of attributes and traits, but because you know each one like you would a close friend or family member -- to the point that you can predict how he or she would respond under certain circumstances.");
        }
        else if (mTotal == 8) {
            aboutTextView.setText("The number 8 is perhaps the most misunderstood of all single-digit numbers, as novices and professionals alike always seem to hammer on the \"money and power\" image of the 8. More often than not, when a client requests a name change consultation, it means he or she wants to add 8s to his or her chart in the mistaken belief that it will bring money and power.\n" +
                    "\n" +
                    "It is true that the number 8, more than any other number, puts the emphasis in the areas of career, business, finances and authority. However, as with many other single-digit numbers, the shape of the number reflects its most important attribute, and in the case of the number 8, that is, first and foremost, balance. The 8 is the great Karmic equalizer, a force that just as easily creates as it destroys. When the 8 comes knocking, you can be assured that you will reap what you've sown.\n" +
                    "\n" +
                    "The 8 balances the material and immaterial worlds. At its best, it is as spiritual as it is materialistic. The spiritual side of the 8 is practical, realistic and intelligent. It knows the difference between make-believe and genuine spiritual realizations. On the material plane, it is focused on results, often in the form of money, yet does not care much about money for the sake of money. It is not greedy, it sees money as a tool, not an end-result. It is generous and willing to take risks. People with strong 8s in their charts often make and lose fortunes a couple of times during their life. They never consider bankruptcy a reason to slow down or feel sorry, but, rather, come out stronger and more success-oriented than before.\n" +
                    "\n" +
                    "Some of the more recognizable traits of the 8 are drive, ambition, authority, efficiency, organization, management, discipline and control. The 8 is goal-oriented, focused, has good judgment, can discriminate and is practical, a realist. Its closest relative is the 1 as both numbers are powerful, have strong leadership skills, are unquestionably masculine and will not shy away from a confrontation. However, where the 1 lacks diplomatic skills and an understanding of human nature -- more typically the traits of the 2 -- the 8 has those abilities as well, which is perhaps the most important reason the 8 tends to do well in business and in authority roles (the military and law enforcement draw a lot of 8s).\n" +
                    "\n" +
                    "When the 8 appears in your personality profile chart, it indicates the presence of the character traits mentioned earlier, as well as the potential to be very successful and prosperous -- hence the reason so many people like to manipulate their charts to add one or more 8s. However, the energy of the 8 needs to be supported by other numbers in order to flourish, such as the 4 to help you keep an eye on the all-important details, and the 9 to keep you in touch with your humanity. So be careful what you ask for. If you decide to change your name to add one or more 8s to your chart, and the rest of your chart does not support this strong force, you may come to inherit more of its negative powers like frustration, dissatisfaction, anger, aggression, greed, intolerance, hate and insomnia. A higher-than-average percentage of 8s find their way into the top echelons of society, but you will also find a disproportionate number of 8s among the homeless.\n" +
                    "\n" +
                    "If the 8 appears in your cycles, especially your Essence cycle, there is an increase in energy and focus, a sense of \"can do,\" and enhanced self-confidence. The shape of the 8 shows balance, but it also shows confidence, as it looks you right in the eye. A positive 8 is honest to a fault, generous and forgiving. They are physically imposing and often athletic, especially good in sports requiring strength and endurance. They are not particularly romantic, as they prefer a practical and straight-forward approach, but they are loving and more than carry their weight.\n" +
                    "\n" +
                    "As with all single-digit numbers, the 8 has a positive and a negative side. However, one of the mysteries of Numerology is that there is a small number of people who, from an early age on and for no discernible reason, seem to turn the exact opposite direction of what their charts indicate. The key word here is \"seem.\" This phenomena is found with all numbers, but appears to affect 8s more than others. There are quite a few people whose charts are dominated with 8s who become priests, missionaries, humanitarians and so forth, but those sacrificing and loving souls do still tend to be good at fundraising, money management and authority.");
        }
        else if (mTotal == 9) {
            aboutTextView.setText("When you multiply any number by 9, then add the resulting digits and reduce them to a single digit, it always becomes a 9. For example, 6 x 9 = 54, reduce 54 to a single digit by adding them together: 5 + 4 = 9. Similarly, 8 x 9 = 72, and 7 + 2 = 9. Or 23 x 9 = 207, 2 + 0 + 7 = 9, and so forth. There is nothing coincidental about this peculiarity. Try it. Any number, no matter how large, multiplied by 9 reduces to 9. From a numerological perspective, the 9 simply takes over, like the infamous body snatchers. Any number that was initially increased by a factor of 9 loses its own identity and instead takes on the characteristics of the 9. No other number has that quality.\n" +
                    "\n" +
                    "A different, but no less distinctive and revealing, attribute of the 9 is that when you add (as opposed to multiply) it to any other number, then reduce that number to a single digit, it always comes back to itself, as if nothing was added at all. For example, 5 + 9 = 14, 1 + 4 = 5. Or 7 + 9 = 16, 1 + 6 = 7. 24 (which reduces to 6) + 9 = 33, 3 + 3 = 6. Again, have some fun, try it on a bunch of numbers.\n" +
                    "\n" +
                    "This, from a numerological perspective, is actually the exact opposite of what happens when you use the 9 to multiply, because when adding it, increasing the amount by 9, it does not change anything to its initial single digit value. When multiplying, the 9 takes over ... when adding, the 9 does nothing. For a math junkie like myself, with a philosophical streak to match, this is pure beauty. It symbolically touches at the core of the magic that underlies this creation. But enough about math, let's look at the personality of this unique number.\n" +
                    "\n" +
                    "The last of the cardinal numbers, the 9 is the most worldly and sophisticated of all numbers. The 9 has some similarities with the 6. However, whereas the 6 as a symbol of motherly (or fatherly) love, giving its love and care to friends, family and the immediate community, the 9 offers it to the world at large; the 9, more than any other number, has global consciousness. Looking at the shape of the symbol is, as always, quite telling. The 9 is like the 6 upside down, a symbol of her offering sympathy and compassion to everyone; a reservoir of giving with a generous downward spout.\n" +
                    "\n" +
                    "The 9 lives in the world and understands the connections between all of mankind. It is a humanitarian, and sees no real difference between its neighbor next door and the person living in a very different culture and environment on the other side of the world. The 9 is the least judgmental of all numbers, the most tolerant and the most conscious. Neither specifically masculine or feminine, the 9 seems more feminine, in large part, because she is so loving and empathetic. She walks like a queen, tall and statuesque, yet feels closely connected with the rest of mankind. At the same time, she is hard to reach, seems aloof and tends to float above the small-minded issues that can be so upsetting to others. You either love her or loathe her, but you can't deny her the respect she demands. She has impeccable taste, is talented and creative, and can be quite eloquent when she expresses herself.\n" +
                    "\n" +
                    "The 9 may be called the the \"Mother Theresa\" number, because when she sees injustice or suffering, she will not hesitate to devote herself to rectifying it. More importantly, she will not dedicate any energy towards receiving credit for her actions; the purity of math that is manifested when she adds to the lives of others is mirrored in the way she goes about doing good: she will not force herself upon others. But when circumstances require, she can be a powerful force, strong enough to take over and bend others to her will (just as she does when she is used to multiply any other number; she takes complete control). Yet she is not a leader in the way both the 1 and the 8 are leaders; her leadership qualities are in the higher realms of philosophy and justice. She changes your mind!\n" +
                    "\n" +
                    "The 9 is often prosperous, but this is one of those contradictions that actually makes sense and illustrates the true nature of the 9 clearly: where the 8 becomes financially successful by focusing on the potential reward from certain undertakings, the 9 earns her financial rewards by completely and utterly ignoring the monetary potential of an endeavor; the exact opposite of the 8.\n" +
                    "\n" +
                    "As for matters of the heart, the 9 is not particularly romantic. She is an impossible lover, not because she is demanding, which she is also, but because you never know to what extent you have managed to reach her. She hides her heart, and even after knowing her for many years, the connection still seems a bit distant. She is a loyal friend but will not allow herself to become vulnerable. The most telling attribute of the 9 is the always subtle and hard to pinpoint sense that there is more to her than meets the eye. A correct observation; she has depth and intuition, and is at all times aware of her surroundings, like a person with over-developed peripheral vision.\n" +
                    "\n" +
                    "As with any number, the 9 has a dark side. She can be condescending, arrogant, cold and apathetic towards the suffering of others. When the 9 shows her dark side, it is egotistic, cruel, immoral and completely untouchable. And unfortunately, it is easy for a 9 to fall into the dark side, like when she perceives herself to have been the victim of an injustice, then she can be vindictive, unforgiving and malicious.\n" +
                    "\n" +
                    "When the 9 appears as a cycle, it often denotes a finality, the completion of an era. The 9 as a cycle is frequently seen as an indicator of death. This is simplistic and wrong. What one or more 9 cycles does suggest is that you are in the final stages of a period or endeavor, that you need to empty your bucket and prepare for the new and that there are opportunities to make a difference. In Personal Year cycles, the 9 is always followed by the 1, and every time you go through that two-year phase, you go through a transformation of some kind. Look at any period in your life when you went through a 9 Personal Year followed by a 1 Personal Year and you will see that this is true. Then look at your Essence and Transit cycles to learn what the fundamental nature of that transformation was.");
        }
        else {
            aboutTextView.setText("Please enter name to know more!");
        }
    }
}


